# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

G <- function(q, n) {
    .Call('_polysat_G', PACKAGE = 'polysat', q, n)
}

INDEXG <- function(ag1, na1, m2) {
    .Call('_polysat_INDEXG', PACKAGE = 'polysat', ag1, na1, m2)
}

GENLIST <- function(ng, na1, m2) {
    .Call('_polysat_GENLIST', PACKAGE = 'polysat', ng, na1, m2)
}

RANMUL <- function(ng, na1, ag, m2) {
    .Call('_polysat_RANMUL', PACKAGE = 'polysat', ng, na1, ag, m2)
}

SELFMAT <- function(ng, na1, ag, m2) {
    .Call('_polysat_SELFMAT', PACKAGE = 'polysat', ng, na1, ag, m2)
}

